CATEGORIES = {
    "Alle Kategorien": "0",
    "Auto, Rad & Boot": "210",
    "Autos": "216",
    "Fahrräder": "217",
    "Motorräder": "305",
    "Elektronik": "161",
    "Handy & Telefon": "173",
    "Haushaltsgeräte": "176",
    "Audio & Hifi": "172",
    "PC & Zubehör": "228",
    "Foto": "245",
    "TV & Video": "175",
    "Haus & Garten": "80",
    "Möbel": "81",
    "Küche & Esszimmer": "86",
    "Lampen & Licht": "82",
    "Schlafzimmer": "83",
    "Wohnzimmer": "88",
    "Mode & Beauty": "153",
    "Damenbekleidung": "154",
    "Herrenbekleidung": "155",
    "Kinder & Familie": "21",
    "Baby- & Kinderkleidung": "22",
    "Spielzeug": "23",
    "Musik, Filme & Bücher": "73",
    "Jobs": "102",
    "Immobilien": "195",
    "Wohnungen mieten": "203",
    "Wohnungen kaufen": "196",
    "Häuser mieten": "205",
    "Häuser kaufen": "208",
    "Zu verschenken & Tauschen": "272",
    "Zu verschenken": "192",
    "Tauschen": "273"
}
